---
# file: gitlab.yml
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: PeterMosmans.bootstrap
      tags: bootstrap
    - role: PeterMosmans.virtualbox-guest
      tags: virtualbox
    - role: PeterMosmans.provision-vagrant
      tags: vagrant
    - role: geerlingguy.gitlab
    - role: PeterMosmans.compact-box
      tags: compact
  vars:
    - gitlab_external_url: "http://gitlab/"
    - gitlab_redirect_http_to_https: "false"
    - gitlab_ssl_certificate: "/etc/gitlab/ssl/gitlab.crt"
    - gitlab_ssl_certificate_key: "/etc/gitlab/ssl/gitlab.key"
    - gitlab_ldap_enabled: "false"
    - hostname: "gitlab"
    - bootstrap_ufw_tcp_allow:
        - 22
        - 80
        - 443
